### ISSUE TITLE
META.yml on CPAN is different than GitHub repo

### ISSUE THREAD

**Issue by duffee** [kilinrax/HTML-Strip#3]
I don't understand why Metacpan doesn't know where the GitHub repo is because the repo's META.yml has a `resources: repository` section, but the META.yml on metacpan doesn't.  It's the reason why you got a patch instead of a PR because I checked there, not here.  <sorry>

Is it that the repository needs to be in the Makefile.PL or is metacpan's indexing just catching up?

No biggie, just thought I was going to add another commit to add the repo and something is already in META.yml. Close this if it doesn't make sense

**Comment by kilinrax** [comment]
META.yml should be in sync with https://github.com/kilinrax/HTML-Strip/commit/a94ac32c861ce63f5203a2c616d143b30a6c7158 and version 2.12 on MetaCPAN.
